steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-f",
        "Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/ws-sync-server"
      - "ws-sync-server-sha256-1=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-2"
